apiVersion: v1
kind: Pod
metadata:
  name: ueransim
  labels:
    app: ueransim
spec:
  containers:
  - name: ueransim
    image: public.ecr.aws/d9j1j8i6/ueransim-debug:latest
    command: ["/bin/sleep", "3650d"]
    imagePullPolicy: IfNotPresent
    securityContext:
      privileged: true
  restartPolicy: Always
